{"$message_type":"diagnostic","message":"failed to remove C:\\Users\\Mario\\Dropbox\\Archivos\\Clase\\Artificial Intelligence\\1st year\\Period 1\\Intelligent Search and Games\\Fianco\\brain\\target\\debug\\deps\\pyo3_build_config-6900cf9187c5e520.pyo3_build_config.d4428b9a79e67d4e-cgu.13.rcgu.o: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso. (os error 32)","code":null,"level":"error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15m: failed to remove C:\\Users\\Mario\\Dropbox\\Archivos\\Clase\\Artificial Intelligence\\1st year\\Period 1\\Intelligent Search and Games\\Fianco\\brain\\target\\debug\\deps\\pyo3_build_config-6900cf9187c5e520.pyo3_build_config.d4428b9a79e67d4e-cgu.13.rcgu.o: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso. (os error 32)\u001b[0m\n\n"}
{"$message_type":"diagnostic","message":"aborting due to 1 previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15m: aborting due to 1 previous error\u001b[0m\n\n"}
